### ISSUE TITLE
[Bug]: Missing return value received when using slices.Delete

### ISSUE THREAD

**Issue by Deleplace** [TelefonicaTC2Tech/golium#119]
Hello, while researching for [this Go proposal](https://github.com/golang/go/issues/62729) I noticed [this code](https://github.com/TelefonicaTC2Tech/golium/blob/77eea8a72e66a0398002d6666629c0b218105dcd/steps/rabbit/session.go#L215):

```
slices.Delete(s.Messages, i, i+1)
```

which probably doesn't behave as intended and should look like this instead:

```
s.Messages = slices.Delete(s.Messages, i, i+1)
```

I have not tried to execute it.

**Comment by ruben-garciad** [comment]
@Deleplace Thanks for your feedback, it's exactly a bug that could affect execution in a corner case.
